version: "3.9"
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=s3,dynamodb,lambda,apigateway
      - DEBUG=1
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      #- DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  backend:
    build:
      context: ./backend
    container_name: backend-app
    ports:
      - "5000:5000"
    environment:
      - AWS_ACCESS_KEY_ID=mock_access_key
      - AWS_SECRET_ACCESS_KEY=mock_secret_key
      - AWS_REGION=us-east-1
      - DYNAMODB_ENDPOINT=http://localstack:4566
    depends_on:
      - localstack
    volumes:
      - ./backend:/app
  
  frontend:
    build:
      context: ./frontend
    container_name: frontend-app
    ports:
      - "8080:80"

networks:
  default:
    name: app-network
